"""
WireGuard key material, generated in-process rather than by shelling out to `wg`.

A WireGuard key is an X25519 key in standard base64: 44 characters that decode to 32 raw
bytes. `cryptography` is already a dependency and already ships X25519, so there is no new
package, no subprocess, no root, and the same code path works on Windows.

Two details that a nearby line of code would get wrong:

- The encoding is *standard* base64, with `+` and `/`. Every other base64 call in this
  project uses `base64.urlsafe_b64encode`, which produces `-` and `_` instead and yields
  keys the `wg` binary rejects.
- X25519 private keys are clamped. `cryptography` stores them already clamped, which is
  what `wg genkey` does too, so a key generated here and a key generated by `wg` are the
  same kind of value and derive the same public key.

Output was compared against wireguard-tools v1.0.20210914 across 500 keys in both
directions with no mismatch. tests/test_wireguard_keys.py pins the RFC 7748 section 6.1
vector so a library change that breaks that compatibility fails the suite instead of
shipping. The minimum `cryptography` version lives in pyproject.toml.
"""

import base64
import binascii
from dataclasses import dataclass

from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey
from cryptography.hazmat.primitives.serialization import (
    Encoding,
    NoEncryption,
    PrivateFormat,
    PublicFormat,
)

# 32 raw bytes, which is 44 base64 characters once the single pad character is counted
KEY_BYTES = 32
KEY_TEXT_LENGTH = 44

_HIDDEN = "<hidden>"


@dataclass(frozen=True, repr=False)
class Keypair:
    """
    A private key and the public key derived from it.

    The private half is kept out of both string forms on purpose. Error messages, log
    events, `rich` tables and the interactive menu all reach for str() or repr() before
    anyone thinks about it, and a private key that reaches a log file has to be treated as
    spent. Read `private_key` explicitly when you actually need it.
    """

    private_key: str
    public_key: str

    def __repr__(self) -> str:
        return f"Keypair(public_key={self.public_key!r}, private_key={_HIDDEN!r})"


def generate_private_key() -> str:
    """
    Return a fresh base64 private key, the same form `wg genkey` produces.

    Returns:
        44 characters of standard base64
    """
    raw = X25519PrivateKey.generate().private_bytes(
        Encoding.Raw, PrivateFormat.Raw, NoEncryption()
    )
    return base64.b64encode(raw).decode("ascii")


def derive_public_key(private_key: str) -> str:
    """
    Return the public key for a private key, the same form `wg pubkey` produces.

    Deriving twice from the same private key gives the same answer; there is no randomness
    on this path.

    Args:
        private_key: A base64 WireGuard private key

    Returns:
        44 characters of standard base64

    Raises:
        ValueError: If the key is not base64 or does not decode to 32 bytes
    """
    raw = _decode_key(private_key, "private key")
    public = X25519PrivateKey.from_private_bytes(raw).public_key()
    return base64.b64encode(public.public_bytes(Encoding.Raw, PublicFormat.Raw)).decode("ascii")


def generate_keypair() -> Keypair:
    """
    Return a new keypair.

    Returns:
        A Keypair whose public key is derived from its private key
    """
    private_key = generate_private_key()
    return Keypair(private_key=private_key, public_key=derive_public_key(private_key))


def is_valid_key(key: str) -> bool:
    """
    Report whether a string is a well-formed WireGuard key.

    Worth calling on anything that arrived from outside, because a public key posted by a
    node during enrollment ends up written straight into the hub config.

    Args:
        key: The candidate key text

    Returns:
        True if it is 44 base64 characters decoding to exactly 32 bytes
    """
    if len(key) != KEY_TEXT_LENGTH:
        return False
    try:
        return len(base64.b64decode(key, validate=True)) == KEY_BYTES
    except (binascii.Error, ValueError):
        return False


def _decode_key(key: str, kind: str) -> bytes:
    """
    Decode a base64 key and check its length.

    The key itself never appears in the error, because this is also the path a malformed
    private key takes and the message ends up in a log.

    Args:
        key: The base64 key text
        kind: What the caller was expecting, used in the error message

    Returns:
        The 32 raw bytes

    Raises:
        ValueError: If the text is not base64 or is the wrong length
    """
    try:
        raw = base64.b64decode(key, validate=True)
    except (binascii.Error, ValueError) as e:
        raise ValueError(f"The {kind} is not valid base64") from e

    if len(raw) != KEY_BYTES:
        raise ValueError(
            f"The {kind} decodes to {len(raw)} bytes; a WireGuard key is {KEY_BYTES} bytes"
        )

    return raw
